# shallow_clone: true

image:
  Visual Studio 2017

build:
  verbosity: detailed

configuration:
  - Debug
platform:
  - x64

branches:
  except:
    - /pr\/.+/

install:
  ############################################################################
  # Update git submodules
  ############################################################################
  - git submodule update --init --recursive

  ############################################################################
  # Install a recent CMake
  ############################################################################
  # - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-win64-x64.zip"
  # - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  # - 7z x cmake.zip -oC:\projects\deps > nul
  # - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  # - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

build_script:
  - cd C:\projects\camstudio
  - IF EXIST build RMDIR /S /Q vs_build
  - MKDIR vs_build
  - cd vs_build
  - cmake ../ -G "Visual Studio 15 2017 Win64" -T host=x64
  - cmake  --build .

